services:
    - type: web
      name: blog-esame
      env: docker
      plan: free
      autoDeploy: true
      buildCommand: ""
      startCommand: ""
      envVars:
          - key: APP_ENV
            value: prod
          - key: DATABASE_URL
            fromDatabase:
                name: blogdb_7c3k
                property: connectionStringInternal

databases:
    - name: blogdb_7c3k
      plan: free
